// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: km/v1/km.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Km_ListUser_FullMethodName = "/v1.Km/ListUser"
)

// KmClient is the client API for Km service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KmClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type kmClient struct {
	cc grpc.ClientConnInterface
}

func NewKmClient(cc grpc.ClientConnInterface) KmClient {
	return &kmClient{cc}
}

func (c *kmClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, Km_ListUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KmServer is the server API for Km service.
// All implementations must embed UnimplementedKmServer
// for forward compatibility
type KmServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedKmServer()
}

// UnimplementedKmServer must be embedded to have forward compatible implementations.
type UnimplementedKmServer struct {
}

func (UnimplementedKmServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedKmServer) mustEmbedUnimplementedKmServer() {}

// UnsafeKmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KmServer will
// result in compilation errors.
type UnsafeKmServer interface {
	mustEmbedUnimplementedKmServer()
}

func RegisterKmServer(s grpc.ServiceRegistrar, srv KmServer) {
	s.RegisterService(&Km_ServiceDesc, srv)
}

func _Km_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Km_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Km_ServiceDesc is the grpc.ServiceDesc for Km service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Km_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Km",
	HandlerType: (*KmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _Km_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "km/v1/km.proto",
}
